### ISSUE TITLE
Генерал де Голль vs Дефис перед «ка», «де», «кась»

### ISSUE THREAD

**Issue by drzl** [typograf/typograf.github.io#12]
Частный случай в котором дефис перед  "де" ошибочен - Шарль де Голль.
После обработки типографом получаем ошибочное "Шарль-де Голль".

**Comment by hcodes** [comment]
Спасибо, сделаю для «де» отдельное правило с учётом фамилий.

https://ru.wikipedia.org/wiki/%D0%A4%D0%B0%D0%BC%D0%B8%D0%BB%D1%8C%D0%BD%D0%B0%D1%8F_%D0%BF%D1%80%D0%B8%D1%81%D1%82%D0%B0%D0%B2%D0%BA%D0%B0#.D0.A4.D1.80.D0.B0.D0.BD.D1.86.D0.B8.D1.8F

**Comment by hcodes** [comment]
Поправил.
https://github.com/typograf/typograf/releases/tag/v4.2.1
