### ISSUE TITLE
Сохранение настроек при выходе из браузера

### ISSUE THREAD

**Issue by vasilkovoe** [typograf/typograf.github.io#15]
Сохранение настроек интерфейса (снятые/отмеченные правила) при выходе из браузера.

**Comment by hcodes** [comment]
Поправил, не сохранялся язык для правил и тип HTML-сущностей.
В каком браузере проблема и воспроизводится ли она сейчас?

**Comment by vasilkovoe** [comment]
**Браузер Firefox 46.0.1.**

Видимо проблема, в том числе, на моей стороне была. При выходе из браузера у меня удалялись куки (указано было в настройках). В этом случае, если выходить из интерфейса настроек https://typograf.github.io/#!prefs  — при выходе/запуске браузера снятые/отмеченные правила сохраняются. При переходе в окно https://typograf.github.io/#!text= и после обработки текста настройки сбрасываются до правил по умолчанию.

При выходе из браузера из интерфейса https://typograf.github.io/#!text= настройки сбрасываются до правил по умолчанию.

С включенными куками отмеченные/снятые правила сохраняются при выходе из Firefox.

***

**Opera 37, Google Chrome 51** — полет нормальный.

**Comment by vasilkovoe** [comment]
Спасибо.

**Comment by hcodes** [comment]
Хорошо, проверю работу с отключенными куками.
