### ISSUE TITLE
При обработке html извлекает кавычки из ссылки

### ISSUE THREAD

**Issue by wofs** [typograf/typograf.github.io#20]
День добрый!

Ссылка вида 
`<a href="link">«Слово»</a>`
после обработки типографом становится
`«<a href="link">Слово</a>»`
такого быть не должно — кавычки это часть ссылки.

**Comment by hcodes** [comment]
https://www.artlebedev.ru/kovodstvo/sections/143/

**Comment by hcodes** [comment]
![изображение](https://user-images.githubusercontent.com/157520/80686264-24e4e500-8ad1-11ea-96ba-641b4e16bc56.png)

**Comment by wofs** [comment]
Спасибо за ответ!
Наверное невнимательно искал.
