### ISSUE TITLE
Расширение для Chrome?

### ISSUE THREAD

**Issue by meanestBreakdown** [typograf/typograf.github.io#42]
Здравствуйте, Денис. Подскажите, пожалуйста, куда пропало расширение из магазина Chrome и планируете ли добавить его обратно?

**Comment by hcodes** [comment]
Расширение устарело, поменялись политики безопасности в Chrome, необходимо переделать данное расширение.

**Comment by meanestBreakdown** [comment]
Спасибо за ответ и с наступающим :)
